rewrote config stuff

diff --git a/prtloc b/prtloc
--- a/prtloc
+++ b/prtloc
@@ -5,8 +5,8 @@
 
 ## CONFIGURATION
 
-# Config location
-set config (cat /etc/prtstuff/config)
+# Set config dir location
+set configdir /etc/prtstuff
 
 
 ## FUNCTIONS
@@ -28,20 +28,23 @@ function location
 	end
 
 	# Alias ports
-	if string match -q -r "^$location " $alias
-		set location (string match -r "^$location .*" $alias | cut -d ' ' -f 2)
+	if string match -q -r "^$location=" $alias
+		set location (string match -r "^$location=.*" $alias | cut -d '=' -f 2)
 	end
 
 	if test -n "$location"
 		echo $location
 	else
-		echo 'Could not find port.'
-		exit
+		echo 'Could not find port.' >/dev/stderr
+		exit 1
 	end
 end
 
 
 ## EXECUTE
+
+# Load config
+source $configdir/config
 
 if test (count $argv) -ge 1
 	for flag in $argv
@@ -52,17 +55,14 @@ if test (count $argv) -ge 1
 				echo '  -h,   --help            print help and exit'
 				exit 0
 			case '*'
-				# Get aliases and order of ports/repos
-				set order (string match -r '^order .*' $config | cut -d ' ' -f 2-)
-				set alias (string match -r '^alias .*' $config | cut -d ' ' -f 2-)
-
 				# Get all ports
+				# TODO: Replace this
 				set ports (ports -l)
 
 				location $argv
 		end
 	end
 else
-	echo 'Please specify a port.'
+	echo 'Please specify a port.' >/dev/stderr
 	exit 1
 end
